$(document).ready(
    function()
    {
        $("div.ui-selectonemenu.full-width").each(
            function()
            {
                $(this).css("width:","250px;");
            }
        );
    }
);